version: '3.5'
services:
  app:
    build:
      context: ../../.
      dockerfile: docker/node/Dockerfile
    container_name: node_react
    restart: unless-stopped
    command:
      - npm start
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
